spring.application.name=cvmanager
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# PROPRIÉTÉS JWT (Étape 3) valable 3 jours
app.jwt-secret=eVgZa6wHUx2f2nY/cq+W3r/+uiGITpZvIBsoZu+Z1QbNNTeCwlvUlsXAD1ECLEjUAe6FhJus6ZSsnOTLb8XQ/w==
app.jwt-expiration-milliseconds=259200000